In [5]:
import numpy as np

In [68]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

###
# Name: Enea DOdi
# Student ID: 2296306
# Email: dodi@chapman.edu
# Course: PHYS220/MATH220/CPSC220 Fall 2018
# Assignment: c209
###

def gradient(x):
        """gradient function
        Args: x - input numpy array consiting of a set of n domain points.
        Returns: a n by n matrix creating a finite difference linear operator"""
        dx = x[1]-x[0]
        ones = np.ones(x.size)
        gradient =np.diag(gradient,2)
        np.fill_diagonal(gradient,1)
        topIndex = np.array(x.size)
        topIndex[0] = 2
        bottomIndex = np.array(x.size)
        bottomIndex[:-1] = -2
        gradient[0] = topIndex
        gradient[:-1] = bottomIndex
        return diagTwo
        
    


In [69]:
l = np.ones(100)
print(gradient(l))
print(square(20))

[[1. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 1.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


IndexError: list assignment index out of range